spring.application.name=10-JWT-HS256
jwt.secret = "a-very-long-256-bit-secret-key-value"
jwt.access-token-ttl-ms=120000
jwt.access-token-ttl-minutes=2

#1000ms = 1s, 60s = 1min = 60*1000 =60000ms
#2m = 2*60000