spring.application.name=multiDb

# JPA Common Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.h2.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# H2 Database Configuration
spring.datasource.h2.jdbc-url=jdbc:h2:mem:testdb
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.username=sa
spring.datasource.h2.password=


# MySQL Database Configuration
spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/companydbz
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.mysql.username=root
spring.datasource.mysql.password=root


