spring.application.name=student-pagination

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#CREATE DATABASE studentdb;
#
#USE studentdb;
#
#CREATE TABLE student (
#id BIGINT PRIMARY KEY AUTO_INCREMENT,
#name VARCHAR(100) NOT NULL,
#email VARCHAR(150) NOT NULL,
#course VARCHAR(100) NOT NULL
#);
#
#
#INSERT INTO student (name, email, course)
#VALUES
#('Amit', 'amit@gmail.com', 'Java'),
#('Rahul', 'rahul@gmail.com', 'Spring Boot'),
#('Vijay', 'vijay@gmail.com', 'Hibernate'),
#('Deepak', 'deepak@gmail.com', 'Java'),
#('Ravi', 'ravi@gmail.com', 'React'),
#('Sanjay', 'sanjay@gmail.com', 'Spring'),
#('Ankit', 'ankit@gmail.com', 'Java'),
#('Karan', 'karan@gmail.com', 'Microservices'),
#('Rohit', 'rohit@gmail.com', 'Kafka'),
#('Manish', 'manish@gmail.com', 'Docker');
#
#GET http://localhost:8080/students?pageNum=1&pageSize=3
#GET http://localhost:8080/students?pageNum=2&pageSize=3