spring.application.name=13-Spring-Scheduling
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true


management.otlp.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.enabled=true
management.tracing.sampling.probability=1.0 
