spring.application.name=02-ORDER-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=04-CONFIG-SERVER
spring.config.import=optional:configserver:
spring.boot.admin.client.url=http://localhost:9090


management.observations.enabled=true
management.tracing.enabled=true
management.endpoints.web.exposure.include=health,info,metrics, refresh
management.tracing.sampling.probability=1.0

